//package org.kopi.ebics.interfaces.h005;
//
//import org.kopi.ebics.certificate.h005.BankCertificateManager;
//import org.kopi.ebics.exception.EbicsException;
//import org.kopi.ebics.session.h005.BankConnectionTraceSession;
//import org.kopi.ebics.session.EbicsSession;
//
//import java.io.IOException;
//import java.security.GeneralSecurityException;
//
//public interface IKeyManager {
//    /**
//     * Sends the user's signature key (A005) to the bank.
//     * After a successful operation, the user is in the "initialized" state.
//     * @throws EbicsException server-generated error message
//     * @throws IOException communication error
//     */
//    void sendINI(EbicsSession ebicsSession, BankConnectionTraceSession traceSession) throws EbicsException, IOException;
//
//    /**
//     * Sends the public part of the protocol keys to the bank.
//     * @throws IOException communication error
//     * @throws EbicsException server-generated error message
//     */
//    void sendHIA(EbicsSession ebicsSession, BankConnectionTraceSession traceSession) throws IOException, EbicsException;
//
//    /**
//     * Sends encryption and authentication keys to the bank.
//     * This order is only allowed for a new user at the bank side that has been created by copying the A005 key.
//     * The keys will be activated immediately after the successful completion of the transfer.
//     * @throws IOException communication error
//     * @throws GeneralSecurityException data decryption error
//     * @throws EbicsException server-generated error message
//     */
//    BankCertificateManager sendHPB(EbicsSession ebicsSession, BankConnectionTraceSession traceSession, String password) throws IOException, GeneralSecurityException, EbicsException;
//
//    /**
//     * Sends the SPR order to the bank.
//     * After that, you have to start over with sending INI and HIA.
//     * @throws IOException Communication exception
//     * @throws EbicsException Error message generated by the bank.
//     */
//    void lockAccess(EbicsSession ebicsSession, BankConnectionTraceSession traceSession) throws IOException, EbicsException;
//}
